# Generated by Django 2.2.4 on 2019-08-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_libro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Libros',
        ),
    ]
